import mirrorkey from 'mirrorkey';

export default mirrorkey([
  'RECOMMENDATION_REQUEST_BEGIN',
  'GET_RECOMMENDATION_END',
  'GET_REWARD_END',
  'GET_PHENO_END',
  'GET_PROGRESS_END',
  'GET_TIPS_END',
  'GET_MAXPOINTS_END',
  'SET_EXCERCISE_COMPLETE_END',
  'SET_HOME_REMEDIES_COMPLETE_END',
  'GET_PROGRESS_POINTS_END',
  'SET_CHANGE_SCHEDULES_END',
  'SET_ACCUPRESSURE_COMPLETE_END',
]);
